[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "require-corp"
    Cross-Origin-Resource-Policy = "cross-origin"
    Access-Control-Allow-Origin = "https://itch.io https://*.itch.io https://*.hwcdn.net"
    Content-Security-Policy = "frame-src 'self' https://itch.io https://*.itch.io https://*.hwcdn.net;"
